In [2]:
import torch
torch.__version__

'2.0.0+cu117'

In [43]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.2778, 0.3135, 0.7340, 0.8536],
        [0.3142, 0.6048, 0.5258, 0.4607],
        [0.8428, 0.7049, 0.4636, 0.6581]])

In [31]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
zeros*random_tensor # element-wise multiplication

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Element-wise multiplication of `tensor1` and `tensor2` will not work when shape components are different, and when on of the tensors doesn't have all 1s in shape components...

In [44]:
zeros = torch.zeros(size=(1, 1))
print(zeros)
zeros * random_tensor

tensor([[0.]])


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

But the below will fail...

In [45]:
zeros = torch.zeros(size=(1, 2))
print(zeros)
zeros * random_tensor

tensor([[0., 0.]])


RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 1

For matrix multiplication we use `torch.Tensor.matmul`

In [46]:
random_tensor_2 = torch.rand(size=(4, 3))
random_tensor_2

tensor([[0.2577, 0.8010, 0.5925],
        [0.2466, 0.4823, 0.2703],
        [0.5491, 0.5307, 0.4801],
        [0.5078, 0.0811, 0.0461]])

In [47]:
random_tensor_2.matmul(random_tensor)

tensor([[0.8226, 0.9829, 0.8850, 0.9789],
        [0.4479, 0.5596, 0.5599, 0.6106],
        [0.7239, 0.8316, 0.9047, 1.0291],
        [0.2054, 0.2408, 0.4368, 0.5012]])

In [50]:
random_tensor_3_1 = torch.rand(size=(2,3, 4))
random_tensor_3_2 = torch.rand(size=(1,4, 3)) # dimension[0] gets broadcasted to fit
random_tensor_3_1.matmul(random_tensor_3_2)

tensor([[[0.5319, 0.8238, 1.3541],
         [0.5162, 0.8844, 1.2540],
         [1.0994, 1.6504, 1.9583]],

        [[0.9502, 1.5143, 1.9786],
         [0.7200, 1.0652, 1.1466],
         [0.7625, 1.1517, 1.2663]]])

In [9]:

torch.rand(size=(2,1,3, 4)).matmul(torch.rand(size=(1,4,4, 3))) 
# different dims in different tensors get broadcasted

tensor([[[[0.6534, 0.5818, 0.8323],
          [0.3535, 0.2946, 0.5658],
          [0.4798, 0.4072, 0.7396]],

         [[1.0125, 0.9407, 1.3370],
          [0.5564, 0.5842, 0.8176],
          [0.7084, 0.5927, 0.9987]],

         [[1.2453, 1.4098, 1.0292],
          [0.7346, 0.9074, 0.6839],
          [0.8923, 1.0539, 0.8310]],

         [[1.1662, 1.3520, 1.3841],
          [0.6457, 0.6556, 0.7017],
          [0.6502, 0.9920, 0.9527]]],


        [[[0.2349, 0.3007, 0.6527],
          [0.4155, 0.5886, 0.5192],
          [0.7150, 0.5960, 0.7187]],

         [[0.4128, 0.5892, 0.8083],
          [0.6547, 0.5395, 0.8581],
          [1.0583, 0.7957, 1.2395]],

         [[0.6336, 0.9908, 0.7978],
          [0.7461, 0.8786, 0.6686],
          [1.2130, 1.2049, 0.8599]],

         [[0.7381, 0.5476, 0.6446],
          [1.0263, 1.3167, 1.2893],
          [0.9965, 1.5060, 1.4434]]]])

In [11]:
torch.zeros(size=(1, 3)) * torch.rand(size=(1,4))

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

In [12]:
# Create a tensor
some_tensor = torch.rand(3, 4, dtype=torch.float64)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU



tensor([[0.7602, 0.8198, 0.6120, 0.0878],
        [0.4233, 0.5677, 0.6903, 0.7071],
        [0.1861, 0.6623, 0.3201, 0.4630]], dtype=torch.float64)
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float64
Device tensor is stored on: cpu


In [13]:
some_tensor.mean()

tensor(0.5250, dtype=torch.float64)

In [17]:
torch.mean(some_tensor.type(torch.float16))

tensor(0.5249, dtype=torch.float16)

In [40]:
some_tensor[torch.arange(end=some_tensor.shape[0]),some_tensor.argmax(dim=1)]

tensor([0.8198, 0.7071, 0.6623], dtype=torch.float64)

In [41]:
some_tensor[some_tensor.argmax(dim=0),torch.arange(end=some_tensor.shape[1])]

tensor([0.7602, 0.8198, 0.6903, 0.7071], dtype=torch.float64)